[package]
name = "ark-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
starknet = "0.3.0"
dotenv = "0.15.0"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8" }
serde = "1.0.164"
aws-config = "0.55.3"
aws-sdk-dynamodb = "0.28.0"
clap = "4.3.8"
structopt = { version = "0.3", default-features = false }
hex = "0.4.3"
